config/routes.rb
Mytest::Application.routes.draw do
  resources :mies

end

app/models/my.rb
class My < ActiveRecord::Base
  attr_accessible :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mies_controller.rb
class MiesController < ApplicationController
  # GET /mies
  # GET /mies.json
  def index
    @mies = My.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mies }
    end
  end

  # GET /mies/1
  # GET /mies/1.json
  def show
    @my = My.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @my }
    end
  end

  # GET /mies/new
  # GET /mies/new.json
  def new
    @my = My.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @my }
    end
  end

  # GET /mies/1/edit
  def edit
    @my = My.find(params[:id])
  end

  # POST /mies
  # POST /mies.json
  def create
    @my = My.new(params[:my])

    respond_to do |format|
      if @my.save
        format.html { redirect_to @my, notice: 'My was successfully created.' }
        format.json { render json: @my, status: :created, location: @my }
      else
        format.html { render action: "new" }
        format.json { render json: @my.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mies/1
  # PUT /mies/1.json
  def update
    @my = My.find(params[:id])

    respond_to do |format|
      if @my.update_attributes(params[:my])
        format.html { redirect_to @my, notice: 'My was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @my.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mies/1
  # DELETE /mies/1.json
  def destroy
    @my = My.find(params[:id])
    @my.destroy

    respond_to do |format|
      format.html { redirect_to mies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mies_helper.rb
module MiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mies/_form.html.erb
<%= form_for(@my) do |f| %>
  <% if @my.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my.errors.count, "error") %> prohibited this my from being saved:</h2>

      <ul>
      <% @my.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mies/edit.html.erb
<h1>Editing my</h1>

<%= render 'form' %>

<%= link_to 'Show', @my %> |
<%= link_to 'Back', mies_path %>

app/views/mies/index.html.erb
<h1>Listing mies</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mies.each do |my| %>
  <tr>
    <td><%= my.title %></td>
    <td><%= link_to 'Show', my %></td>
    <td><%= link_to 'Edit', edit_my_path(my) %></td>
    <td><%= link_to 'Destroy', my, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New My', new_my_path %>

app/views/mies/new.html.erb
<h1>New my</h1>

<%= render 'form' %>

<%= link_to 'Back', mies_path %>

app/views/mies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @my.title %>
</p>


<%= link_to 'Edit', edit_my_path(@my) %> |
<%= link_to 'Back', mies_path %>